name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDU4NzY2YjQtZDVlNC00ZTM3LWJlMDItMDYzZDU3OWE3Mzk5IiwidGVuYW50X2lkIjoiOTE3ZTc1MTAzZDRjOGQyNTFiOTc1N2FmNmUyMmM0YjNkMTg2MWJkYTZkMWNlZDJhYTg2NTVkZTVkMDE0NWIyNiIsImludGVybmFsX3NlY3JldCI6IjVjMTQyODE2LTY1MjctNDliMS05N2ZhLTEyNDY1ZWJlOTVjNyJ9.WaWmPaIDcVmP-Vb8GO95mDDtgzMBU5Y8oRoyX5Lura8"

JWT_SECRET="blogjwtkey"